using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.UI.Lobby
{
    [GenerateTypedNameReferences]
    public partial class LobbyHud : Control
    {

    }
}
