using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UI.Chat
{
    [GenerateTypedNameReferences]
    public partial class ChatBox : Control
    {
        public ChatBox()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
