using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.UI.Connecting
{
    [GenerateTypedNameReferences]
    public partial class ConnectingHud : Control
    {
        public Label Message => MessageLabel;
        public Button Reconnect => ReconnectButton;

        public void ShowMessage(string message)
        {
            Message.Text = message;
            Message.Visible = true;
        }

        public void HideMessage()
        {
            Message.Text = string.Empty;
            Message.Visible = false;
        }
    }
}
